# SPDX-FileCopyrightText: 2021-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

title: WeeChat specifications
descriptions: A collection of specifications for WeeChat
