# SPDX-FileCopyrightText: 2021-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

version = 1

[[annotations]]
path = "CNAME"
precedence = "override"
SPDX-FileCopyrightText = "2021-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
